arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - carriage_joint
    - robot_base_joint
    - robot_arm_joint
    - robot_forearm_joint
    - robot_wrist_joint
  gains:
    carriage_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1